### ISSUE TITLE
request method OPTIONS not supported?

### ISSUE THREAD

**Issue by V1os** [nostop8/yii2-rest-api-doc#2]
PHP Notice – yii\base\ErrorException
Undefined index: OPTIONS

                [
                    'class'         => 'yii\rest\UrlRule',
                    'controller'    => 'nameController',
                    'extraPatterns' => [
                        'GET total'           => 'total',
                        'OPTIONS total'       => 'options'
                    ],
                ],

**Comment by nostop8** [comment]
Thanks for report. The issue should be resolved now.
