### ISSUE TITLE
Запуск yii2-rest-api-doc

### ISSUE THREAD

**Issue by Mcavoy2** [nostop8/yii2-rest-api-doc#3]
Установил через компосер -> прописал в конфиге все по инструкции 
перехожу на страницу site.name/documentation, получаю вот что: [link](http://joxi.ru/p27onXofoe55e2)
как двигаться дальше не пойму.

**Comment by nostop8** [comment]
have you tried to define some REST routes in your application? This is a quote from instruction:

> First of all you should know that this documentation generator will work only in case you define your REST API endpoints using following principles: http://www.yiiframework.com/doc-2.0/guide-rest-routing.html
